### ISSUE TITLE
The program doesn't run (Java version mismatch)

### ISSUE THREAD

**Issue by Yoti** [teras/Jubler#31]
According the website the program is written in Java 1.5.0.
```
It is open source under a liberal (GNU) public license. It is written in Java 5.0 (a.k.a. Java 1.5.0) in order to be really multi-platform. It has been tested under Linux, Windows XP and Mac OS X.
```
But even if I have Java 1.8 (Version 8 Update 381) on my Windows 11 Pro it doesn't run:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Jubler has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```
Oracle Docs says that Java 1.5 is class version 49, but we see that program has class version 58 (Java 14).

**Comment by teras** [comment]
This has been fixed in latest versions of Jubler. The new release will support Java 8.
